cache:
  directories:
  - cache
  - dependencies
language: java
matrix:
  include:
    - env: ELIXIR_VERSION="1.4.0" IDEA_TARBALL_ROOT_BASENAME="idea-IC-163.9166.29" IDEA_VERSION="2016.3.1"
      jdk: oraclejdk8
    - env: ELIXIR_VERSION="1.3.4" IDEA_TARBALL_ROOT_BASENAME="idea-IC-163.9166.29" IDEA_VERSION="2016.3.1"
      jdk: oraclejdk8
    - env: ELIXIR_VERSION="1.2.6" IDEA_TARBALL_ROOT_BASENAME="idea-IC-163.9166.29" IDEA_VERSION="2016.3.1"
      jdk: oraclejdk8
    - env: ELIXIR_VERSION="1.1.1" IDEA_TARBALL_ROOT_BASENAME="idea-IC-163.9166.29" IDEA_VERSION="2016.3.1"
      jdk: oraclejdk8

    - env: ELIXIR_VERSION="1.4.0" IDEA_TARBALL_ROOT_BASENAME="idea-IC-143.2370.31" IDEA_VERSION="15.0.6"
      jdk: oraclejdk8
    - env: ELIXIR_VERSION="1.3.4" IDEA_TARBALL_ROOT_BASENAME="idea-IC-143.2370.31" IDEA_VERSION="15.0.6"
      jdk: oraclejdk8
    - env: ELIXIR_VERSION="1.2.6" IDEA_TARBALL_ROOT_BASENAME="idea-IC-143.2370.31" IDEA_VERSION="15.0.6"
      jdk: oraclejdk8
    - env: ELIXIR_VERSION="1.1.1" IDEA_TARBALL_ROOT_BASENAME="idea-IC-143.2370.31" IDEA_VERSION="15.0.6"
      jdk: oraclejdk8

    - env: ELIXIR_VERSION="1.4.0" IDEA_TARBALL_ROOT_BASENAME="idea-IC-141.3056.4" IDEA_VERSION="14.1.6"
      jdk: openjdk6
    - env: ELIXIR_VERSION="1.3.4" IDEA_TARBALL_ROOT_BASENAME="idea-IC-141.3056.4" IDEA_VERSION="14.1.6"
      jdk: openjdk6
    - env: ELIXIR_VERSION="1.2.6" IDEA_TARBALL_ROOT_BASENAME="idea-IC-141.3056.4" IDEA_VERSION="14.1.6"
      jdk: openjdk6
    - env: ELIXIR_VERSION="1.1.1" IDEA_TARBALL_ROOT_BASENAME="idea-IC-141.3056.4" IDEA_VERSION="14.1.6"
      jdk: openjdk6
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
install:
  - if [ ! -f cache/erlang/18.3/activate ]; then curl -O https://raw.githubusercontent.com/yrashk/kerl/master/kerl && chmod a+x kerl && ./kerl update releases && travis_wait $PWD/kerl build 18.3 18.3 && ./kerl install 18.3 cache/erlang/18.3; fi
  - source cache/erlang/18.3/activate
  - ant -logger org.apache.tools.ant.listener.AnsiColorLogger -f intellij-elixir.xml get.idea get.intellij-erlang release.intellij_elixir
script:  ant -logger org.apache.tools.ant.listener.AnsiColorLogger -f intellij-elixir.xml test.modules
sudo: false
